### ISSUE TITLE
where to obtain `org_id`

### ISSUE THREAD

**Issue by zmzlois** [axiomhq/axiom-go#290]
me stupid, already figured out but...

when README.md mention about `AXIOM_ORG_ID` it should mention it's the simple string under your organisation's name in setting's page, otherwise I have been hunting for a long uuid with title `Organisation Id` on settings' page and found nothing. 

when you provide me a click to copy button it doesn't indicate anything that is an org id, I only found out after I 
1. ran `axiom --help` and in the `FLAGS` it told me what's my org id
2. google `axiom org id` and found [this blog](https://axiom.co/changelog/expose-org-id), this should be under any sdk uses or mention `org_id`

little thing, could save people minutes

**Comment by lukasmalkmus** [comment]
Thanks for the report! Is [this change](https://github.com/axiomhq/axiom-go/pull/291) helpful? I added a better explanation to the README in an info box for better visibility:

<img width="977" alt="Screenshot 2024-02-28 at 13 12 40" src="https://github.com/axiomhq/axiom-go/assets/9931588/aaca7606-d8e7-4a3b-a043-c6a981b50f53">

**Comment by zmzlois** [comment]
Looks good! (apply standard Axiom PR format)
```

#           _             _            _            _   _       
#          _\ \          /\ \         /\ \         /\_\/\_\ _   
#         /\__ \        /  \ \        \_\ \       / / / / //\_\ 
#        / /_ \_\      / /\ \_\       /\__ \     /\ \/ \ \/ / / 
#       / / /\/_/     / / /\/_/      / /_ \ \   /  \____\__/ /  
#      / / /         / / / ______   / / /\ \ \ / /\/________/   
#     / / /         / / / /\_____\ / / /  \/_// / /\/_// / /    
#    / / / ____    / / /  \/____ // / /      / / /    / / /     
#   / /_/_/ ___/\ / / /_____/ / // / /      / / /    / / /      
#  /_______/\__\// / /______\/ //_/ /       \/_/    / / /       
#  \_______\/    \/___________/ \_\/                \/_/        
#                                                               


```

 maybe even also : if you are on `Axiom CLI` do `axiom --help` and see the default value in **FLAGS** section (ideally `CLI` should have an option to let me see my current config cred or where the config file is)

_Example_

<hr/>
<dl>
<dt>AXIOM_TOKEN</dt>
<dd>Personal token created under ...</dd>
<dt>AXIOM_ORG_ID</dt>
<dd>Value under organization full name...click to copy</dd>
</dl>

<hr/>
or 

| Name | Value |
|----|----|
| `AXIOM_TOKEN`| Personal token created under ...|
| `AXIOM_ORG_ID`| Value under organization full name ...click to copy|

<hr/>
or 

#### Find `AXIOM_ORG_ID` 
- Your organization ID is the slug below your organization full name in .... click on it to copy the value. 
- Optional: You can also extract it from any URL on the app: ...
- Optional: Run `axiom --help` with `Axiom CLI` to see the default values of your organization ID and auth token(the `AXIOM_TOKEN`) under the **FLAGS** secion
