### ISSUE TITLE
Not compatible with latest go.opentelemetry.io/otel version(s)

### ISSUE THREAD

**Issue by Flo4604** [axiomhq/axiom-go#314]
I recently upgraded all my go packages one of those updates were alot of go.opentelemetry.io/otel/ modules 

my go mod file
[go_mod.txt](https://github.com/user-attachments/files/15537634/go_mod.txt)

currently using `github.com/axiomhq/axiom-go v0.18.0`

And I am getting `conflicting Schema URL: https://opentelemetry.io/schemas/1.25.0 and https://opentelemetry.io/schemas/1.24.0` which is most likely caused by https://github.com/axiomhq/axiom-go/blob/06adf551248b9431dc86bb3df306c27aa1353952/axiom/otel/trace.go#L17

After downgrading some of the otel modules to 1.24.0 instead of 1.27.0 it works again

**Comment by lukasmalkmus** [comment]
Ups, my bad. There recently was a new OTel release that bumped the `semconv` package they import in the SDK. The way we create the "resource" conflicts if we are not in sync with that import statement. There even is a comment about it in our source code.

In the future I want to implement a better approach to get rid of that relationship as this forces OTel and Axiom users to keep specific versions of OTel and Axiom in sync.

But for now, it's sane to fix this by bumping OTel to the latest release and updating to `semconv@1.25.0`.

I created [this](https://github.com/axiomhq/axiom-go/pull/315) PR.

**Comment by lukasmalkmus** [comment]
Going to tag `v0.18.1` once all tests on `main` are good.

**Comment by Flo4604** [comment]
thanks!
