### ISSUE TITLE
add queries docs to axiom-go 

### ISSUE THREAD

**Issue by thecraftman** [axiomhq/axiom-go#85]
https://pkg.go.dev/github.com/axiomhq/axiom-go/axiom

**Comment by lukasmalkmus** [comment]
Can you elaborate what is missing?

**Comment by thecraftman** [comment]
@lukasmalkmus i updated fixes here https://github.com/axiomhq/axiom-go/pull/89/files

**Comment by lukasmalkmus** [comment]
Will be closed by #96.
